name: export-and-branch-solution
# Export solution from DEV environment
#Â  unpack it and prepare, commit and push a git branch with the changes
on:
  workflow_dispatch:
    inputs:
    # Change this value
    solution_name:
      description: 'name of the solution to worked on from Power Platform'
      required: true
      default: contoso_university_core
    #Do Not change these values
    solution_exported_folder:
      description: 'folder name for staging the exported solution *do not change*'
      required: true
      default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'folder name to be created and checked in *do not change*'
        required: true
        default: solutions/

jobs:
  export-from-dev:
    runs-on: windows-latest
    environment: production

  env:
    RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
      lfs: true
      
    - name: export-solution action -unmanaged
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: https://org56bc8f2e.crm11.dynamics.com/
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.DEPLOY_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: export-solution action -managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: https://org56bc8f2e.crm11.dynamics.com/
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.DEPLOY_SECRET }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        managed: true
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Both'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true